/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.beans.PropertyVetoException;
import javax.swing.JInternalFrame;

/**
 * @author 631120345
 */
public class MainView extends javax.swing.JFrame {

    JIntFrameCadSala cadSala = new JIntFrameCadSala();
    JIntFrameCadFilme cadFilme = new JIntFrameCadFilme();
    jIntFrameCadSessao cadSessao = new jIntFrameCadSessao();
    jIntFrameRegVenda regVenda = new jIntFrameRegVenda();

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem7 = new javax.swing.JMenuItem();
        jDeskPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eco-Cinema");
        setResizable(false);

        jDeskPane.setMaximumSize(new java.awt.Dimension(575, 537));
        jDeskPane.setMinimumSize(new java.awt.Dimension(575, 537));

        javax.swing.GroupLayout jDeskPaneLayout = new javax.swing.GroupLayout(jDeskPane);
        jDeskPane.setLayout(jDeskPaneLayout);
        jDeskPaneLayout.setHorizontalGroup(
            jDeskPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );
        jDeskPaneLayout.setVerticalGroup(
            jDeskPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastros");

        jMenu7.setText("Sala");

        jMenuItem9.setText("Cadastrar");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem9);

        jMenu1.add(jMenu7);

        jMenu8.setText("Filme");

        jMenuItem11.setText("Cadastrar");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem11);

        jMenu1.add(jMenu8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Operações");

        jMenuItem4.setText("Vendas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDeskPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDeskPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        carregaTelas(cadSala);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        carregaTelas(cadFilme);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        carregaTelas(regVenda);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * Realiza o carregamento de forma adequada das telas.
     *
     * @param tela Componente que será carretado
     */
    private void carregaTelas(JInternalFrame tela) {
        if (tela.isShowing()) {
            tela.dispose();
            jDeskPane.remove(tela);
        }
        jDeskPane.add(tela);
        tela.setVisible(true);
        try {
            tela.setMaximum(true);
        } catch (PropertyVetoException ex) {
            PrintUtil.printMessageErro(this, ex);
        }
    }

    /**
     * @deprecated - generalizado.
     * @see - Method carregaTelas
     */
    private void telaCadSala() {
        if (cadSala.isShowing()) {
            cadSala.dispose();
            jDeskPane.remove(cadSala);
        }
        jDeskPane.add(cadSala);
        cadSala.setVisible(true);
        try {
            cadSala.setMaximum(true);
        } catch (PropertyVetoException ex) {
            PrintUtil.printMessageErro(this, ex);
        }
    }

    /**
     * @deprecated - generalizado.
     * @see - Method carregaTelas
     */
    private void telaCadFilme() {
        if (cadFilme.isShowing()) {
            cadFilme.dispose();
            jDeskPane.remove(cadFilme);
        }
        jDeskPane.add(cadFilme);
        cadFilme.setVisible(true);
        try {
            cadFilme.setMaximum(true);
        } catch (PropertyVetoException ex) {
            PrintUtil.printMessageErro(this, ex);
        }
    }

    public void exec() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        new MainView().setVisible(true);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDeskPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables

}
